### ISSUE TITLE
Didn't recognize rgb(100%,100%,100%)

### ISSUE THREAD

**Issue by ariutta** [yetzt/node-rgbcolor#11]
Hi there, thanks for making this library! I wanted to check -- should this library handle [SVG colors](https://www.w3.org/TR/SVG/types.html#DataTypeColor)? Right now, it returns false for this value:

```js
var RGBColor = require("rgbcolor");
const color = new RGBColor("rgb(100%,100%,100%)");
if (!color.ok) {
	throw new Error("Did not recognize this input")
       // => throws error
}
```

**Comment by yetzt** [comment]
i didn't make this library, it's from [here](http://www.phpied.com/rgb-color-parser-in-javascript/) and i just put it to npm. but i'll be happy to merge a pull request with a fix.

**Comment by ariutta** [comment]
I don't want to bloat the lib if no one else needs SVG colors included, so let's table it for now. But if anyone else wants them included, I can make a pull request.
