### ISSUE TITLE
Parse rgba() values

### ISSUE THREAD

**Issue by floledermann** [yetzt/node-rgbcolor#4]
For processing CSS it would be great if parsing alpha values was supported. I could contribute to this, however I am not sure what would be the best, backwards-compatible way to support this? Maybe just introduce `this.alpha = 1.0`, and add `toRGBA()` method?

**Comment by yetzt** [comment]
i'll lokk into it, pull requests welcome :)

**Comment by yetzt** [comment]
merged and published. :)
